### ISSUE TITLE
前台web解密还是提示license异常,无法使用web功能

### ISSUE THREAD

**Issue by jhtshr** [rrrrrrri/fos-license-gen#1]
前台web解密还是提示license异常,无法使用web功能,cli里都显示正常了,

**Comment by rrrrrrri** [comment]
请提供系统版本、错误截图等具体信息。

**Comment by jhtshr** [comment]
官网 FortiGate 7.2.4 for VMware
FGT_VM64-v7.2.4.F-build1396-FORTINET.out.ovf

keygen以后license在cli中的状态
`FGVMEVBO7H1QME99 # diagnose debug vm-print-license
SerialNumber: FGVMEVBO7H1QME99
CreateDate: Wed Mar  1 08:00:00 2023
License expires: Tue May 29 23:00:16 -1227700
Expiry: 5172480
LENC: yes
CARRIER: yes
Model: EVAL (1)
CPU: 1
MEM: 2048
VDOM license:
  permanent: 2
  subscription: 0

FGVMEVBO7H1QME99 #

`
web提示和没有license是一样的

VM is not licensed or license is invalid for current VM configuration. Upload a new license or reconfigure the VM.

**Comment by jhtshr** [comment]
cli里用 get system  status命令看,license还是非法状态

License Status: Invalid

**Comment by rrrrrrri** [comment]
> cli里用 get system status命令看,license还是非法状态
> 
> License Status: Invalid

我这里测试没有问题。

**Comment by jhtshr** [comment]
我这里参数可能设置错误了,刚也试了一下,确实可以了,谢谢

**Comment by ZoEplA** [comment]
我使用的是 FortiGate 7.2.4 for KVM的环境，我只修改了脚本里的SERIALNO和CREATEDATE的内容，如下所示

    license_data_list = [
                            LicenseDataBlock("SERIALNO", "FGVMEV0000000000"),
                            # LicenseDataBlock("CERT", "CERT"),
                            # LicenseDataBlock("KEY", "KEY"),
                            # LicenseDataBlock("CERT2", "CERT2"),
                            # LicenseDataBlock("KEY2", "KEY2"),
                            LicenseDataBlock("CREATEDATE", "1681960921"),
                            # LicenseDataBlock("UUID", "UUID"),
                            # LicenseDataBlock("CONTRACT", "CONTRACT"),
                            LicenseDataBlock("USGFACTORY", "32"),
                            LicenseDataBlock("LENCFACTORY", "32"),
                            LicenseDataBlock("CARRIERFACTORY", "32"),
                            LicenseDataBlock("EXPIRY", "15552000"),
                        ]

上传后机器状态如下，似乎依然没有校验成功：

FGVMEV0000000000 # get system status 
Version: FortiGate-VM64-KVM v7.2.4,build1396,230131 (GA.F)
Virus-DB: 1.00000(2018-04-09 18:07)
Extended DB: 1.00000(2018-04-09 18:07)
Extreme DB: 1.00000(2018-04-09 18:07)
AV AI/ML Model: 0.00000(2001-01-01 00:00)
IPS-DB: 6.00741(2015-12-01 02:30)
IPS-ETDB: 6.00741(2015-12-01 02:30)
APP-DB: 6.00741(2015-12-01 02:30)
INDUSTRIAL-DB: 6.00741(2015-12-01 02:30)
IPS Malicious URL Database: 1.00001(2015-01-01 01:01)
IoT-Detect: 0.00000(2022-08-17 17:31)
Serial-Number: FGVMEV0000000000
License Status: Invalid
License Expiration Date: 4703304-07-13
VM Resources: 1 CPU/1 allowed, 1993 MB RAM/2048 MB allowed
Log hard disk: Not available
Hostname: FGVMEV0000000000
Operation Mode: NAT
Current virtual domain: root
Max number of virtual domains: 2
Virtual domains status: 1 in NAT mode, 0 in TP mode
Virtual domain configuration: disable
FIPS-CC mode: disable
Current HA mode: standalone
Branch point: 1396
Release Version Information: GA
FortiOS x86-64: Yes
System time: Wed Apr 19 22:40:37 2023
Last reboot reason: warm reboot

FGVMEV0000000000 # 
FGVMEV0000000000 # 
FGVMEV0000000000 # diagnose debug vm-print-license 
SerialNumber: FGVMEV0000000000
CreateDate: Wed Apr 19 20:22:01 2023
License expires: Sun Jul 13 23:00:16 4703304
Expiry: 5172480
LENC: yes
CARRIER: yes
Model: EVAL (1)
CPU: 1 
MEM: 2048
VDOM license:
  permanent: 2
  subscription: 0

FGVMEV0000000000 # 

你们知道原因吗？我这个设备上应该无法连接外网！谢谢~
