### ISSUE TITLE
VM shuting down FortiOS 7.2.4 

### ISSUE THREAD

**Issue by phg-91** [rrrrrrri/fos-license-gen#6]
When using the generated license on an Azure VM, the appliance shuts down immediately after deployment. This behavior starts on FortiOS 7.2.4. Has an advanced license verification process been implemented?

**Comment by rrrrrrri** [comment]
> When using the generated license on an Azure VM, the appliance shuts down immediately after deployment. This behavior starts on FortiOS 7.2.4. Has an advanced license verification process been implemented?

Sorry, I only tested the script on FortiOS VMware version. It works fine on version 7.2.4. I am not sure if the license verification process is different on Azure VM appliance.

**Comment by phg-91** [comment]
Thank you for your great work.
