### ISSUE TITLE
FFW_VM64-v7.4.0.F-build2360-FORTINET 使用这个lic.txt失败了

### ISSUE THREAD

**Issue by Endt4sk** [rrrrrrri/fos-license-gen#8]
我使用
license_data_list = [
                        LicenseDataBlock("SERIALNO", "FGVMPG1234567890"),
                        # LicenseDataBlock("CERT", "CERT"),
                        # LicenseDataBlock("KEY", "KEY"),
                        # LicenseDataBlock("CERT2", "CERT2"),
                        # LicenseDataBlock("KEY2", "KEY2"),
                        LicenseDataBlock("CREATEDATE", "1688587024"),
                        # LicenseDataBlock("UUID", "UUID"),
                        # LicenseDataBlock("CONTRACT", "CONTRACT"),
                        LicenseDataBlock("USGFACTORY", "32"),
                        LicenseDataBlock("LENCFACTORY", "32"),
                        LicenseDataBlock("CARRIERFACTORY", "32"),
                        LicenseDataBlock("EXPIRY", "1691265424"),
                    ]
这样填写对吗？

**Comment by rrrrrrri** [comment]
> 我使用 license_data_list = [ LicenseDataBlock("SERIALNO", "FGVMPG1234567890"), # LicenseDataBlock("CERT", "CERT"), # LicenseDataBlock("KEY", "KEY"), # LicenseDataBlock("CERT2", "CERT2"), # LicenseDataBlock("KEY2", "KEY2"), LicenseDataBlock("CREATEDATE", "1688587024"), # LicenseDataBlock("UUID", "UUID"), # LicenseDataBlock("CONTRACT", "CONTRACT"), LicenseDataBlock("USGFACTORY", "32"), LicenseDataBlock("LENCFACTORY", "32"), LicenseDataBlock("CARRIERFACTORY", "32"), LicenseDataBlock("EXPIRY", "1691265424"), ] 这样填写对吗？

7.4.0 似乎更换了 license 校验逻辑，此工具生成的文件暂时无法使用。

**Comment by Endt4sk** [comment]
> > 我使用 license_data_list = [ LicenseDataBlock("SERIALNO", "FGVMPG1234567890"), # LicenseDataBlock("CERT", "CERT"), # LicenseDataBlock("KEY", "KEY"), # LicenseDataBlock("CERT2", "CERT2"), # LicenseDataBlock("KEY2", "KEY2"), LicenseDataBlock("CREATEDATE", "1688587024"), # LicenseDataBlock("UUID", "UUID"), # LicenseDataBlock("CONTRACT", "CONTRACT"), LicenseDataBlock("USGFACTORY", "32"), LicenseDataBlock("LENCFACTORY", "32"), LicenseDataBlock("CARRIERFACTORY", "32"), LicenseDataBlock("EXPIRY", "1691265424"), ] 这样填写对吗？
> 
> 7.4.0 似乎更换了 license 校验逻辑，此工具生成的文件暂时无法使用。

我换成7.2.5成功了，大佬能做下7.4.0的吗？

**Comment by rrrrrrri** [comment]
> > > 我使用 license_data_list = [ LicenseDataBlock("SERIALNO", "FGVMPG1234567890"), # LicenseDataBlock("CERT", "CERT"), # LicenseDataBlock("KEY", "KEY"), # LicenseDataBlock("CERT2", "CERT2"), # LicenseDataBlock("KEY2", "KEY2"), LicenseDataBlock("CREATEDATE", "1688587024"), # LicenseDataBlock("UUID", "UUID"), # LicenseDataBlock("CONTRACT", "CONTRACT"), LicenseDataBlock("USGFACTORY", "32"), LicenseDataBlock("LENCFACTORY", "32"), LicenseDataBlock("CARRIERFACTORY", "32"), LicenseDataBlock("EXPIRY", "1691265424"), ] 这样填写对吗？
> > 
> > 
> > 7.4.0 似乎更换了 license 校验逻辑，此工具生成的文件暂时无法使用。
> 
> 我换成7.2.5成功了，大佬能做下7.4.0的吗？

可能会在空闲时间做下研究，你也可以尝试自行分析。

**Comment by rrrrrrri** [comment]
> > > 我使用 license_data_list = [ LicenseDataBlock("SERIALNO", "FGVMPG1234567890"), # LicenseDataBlock("CERT", "CERT"), # LicenseDataBlock("KEY", "KEY"), # LicenseDataBlock("CERT2", "CERT2"), # LicenseDataBlock("KEY2", "KEY2"), LicenseDataBlock("CREATEDATE", "1688587024"), # LicenseDataBlock("UUID", "UUID"), # LicenseDataBlock("CONTRACT", "CONTRACT"), LicenseDataBlock("USGFACTORY", "32"), LicenseDataBlock("LENCFACTORY", "32"), LicenseDataBlock("CARRIERFACTORY", "32"), LicenseDataBlock("EXPIRY", "1691265424"), ] 这样填写对吗？
> > 
> > 
> > 7.4.0 似乎更换了 license 校验逻辑，此工具生成的文件暂时无法使用。
> 
> 我换成7.2.5成功了，大佬能做下7.4.0的吗？

FGT 7.4.0 使用此工具生成的 license 似乎可以正常使用，FFW 超出讨论范围。
