### ISSUE TITLE
VMDK version 3 must be read only

### ISSUE THREAD

**Issue by kyo-w** [rrrrrrri/fos-license-gen#9]
新人求问，打包好的rootft.gz怎么替换原先VMDK里面的rootft.gz

**Comment by rrrrrrri** [comment]
> 新人求问，打包好的rootft.gz怎么替换原先VMDK里面的rootft.gz

直接覆盖原始文件。

**Comment by kyo-w** [comment]
为什么我写入被拒绝了，显示只读

**Comment by rrrrrrri** [comment]
> 为什么我写入被拒绝了，显示只读

你没有提到目标系统是哪个版本，以及你的研究环境等具体信息。我建议你检查一下磁盘挂载的是否正确，尽量使用 ubuntu 系统来修改，正常情况下分区都是可写的。

**Comment by kyo-w** [comment]
现在官方最新版
环境：Ubuntu16.04，QEMU
我挂载的是，fortios.vmdk。是不是得vmware安装ovf后的磁盘

**Comment by rrrrrrri** [comment]
> 现在官方最新版 环境：Ubuntu16.04，QEMU 我挂载的是，fortios.vmdk。是不是得vmware安装ovf后的磁盘

是的要修改安装好系统之后的磁盘。

**Comment by kyo-w** [comment]
感谢
